tablero = [
    # Casillas 1-15 (lado izquierdo - serpientes)
    {"numero": 1, "tipo": "normal"},
    {"numero": 2, "tipo": "serpiente_verde"},
    {"numero": 3, "tipo": "normal"},
    {"numero": 4, "tipo": "serpiente_roja"},
    {"numero": 5, "tipo": "normal"},
    {"numero": 6, "tipo": "serpiente_verde"},
    {"numero": 7, "tipo": "normal"},
    {"numero": 8, "tipo": "serpiente_roja"},
    {"numero": 9, "tipo": "normal"},
    {"numero": 10, "tipo": "serpiente_verde"},
    {"numero": 11, "tipo": "normal"},
    {"numero": 12, "tipo": "serpiente_roja"},
    {"numero": 13, "tipo": "normal"},
    {"numero": 14, "tipo": "serpiente_verde"},
    {"numero": 15, "tipo": "normal"},
    
    # Casillas 16-30 (lado derecho - escaleras)
    {"numero": 16, "tipo": "escalera_normal"},
    {"numero": 17, "tipo": "normal"},
    {"numero": 18, "tipo": "escalera_dorada"},
    {"numero": 19, "tipo": "normal"},
    {"numero": 20, "tipo": "escalera_normal"},
    {"numero": 21, "tipo": "normal"},
    {"numero": 22, "tipo": "escalera_dorada"},
    {"numero": 23, "tipo": "normal"},
    {"numero": 24, "tipo": "escalera_normal"},
    {"numero": 25, "tipo": "normal"},
    {"numero": 26, "tipo": "escalera_dorada"},
    {"numero": 27, "tipo": "normal"},
    {"numero": 28, "tipo": "escalera_normal"},
    {"numero": 29, "tipo": "normal"},
    {"numero": 30, "tipo": "final"}
]